version: "3.5"
services:
  app:
    environment:
      S3_HOST: ${S3_CNAME}
      S3_LOCAL: "yes"
    volumes:
      - ./config/lab-eula.yml:/aquarium/config/user_agreement.yml

  s3:
    ports:
      - "${S3_PUBLIC_PORT}:9000"
    environment:
      VIRTUAL_HOST: ${S3_CNAME}
      VIRTUAL_PORT: ${S3_PUBLIC_PORT}
      LETSENSCRYPT_HOST: ${S3_CNAME}
      LETSENSCRYPT_EMAIL: ${LETSENCRYPT_ADMIN_EMAIL}
    networks:
      - deploy_net

  web:
    networks:
      - deploy_net
    environment:
      VIRTUAL_HOST: ${APP_CNAME}
      VIRTUAL_PORT: ${APP_PUBLIC_PORT}
      LETSENSCRYPT_HOST: ${APP_CNAME}
      LETSENSCRYPT_EMAIL: ${LETSENCRYPT_ADMIN_EMAIL}
    volumes:
      - ./config/nginx.deploy.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  deploy_net:
    external:
      name: dockernet
