version: "3.5"
services:
  app:
    environment:
      S3_LOCAL: "yes"
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.route_localnet=1

  krill:
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.route_localnet=1

  web:
    volumes:
      - ./config/nginx.local.conf:/etc/nginx/conf.d/default.conf:ro
