version: "3.5"
services:
  app:
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: ${TIMEZONE}
    volumes:
      - ./data/db:/var/lib/mysql
      - ./data/mysql_init/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - aquarium_net

  krill:
    depends_on:
      - db
 
  


